
export interface NavItem {
  name: string;
  path?: string;
  subItems?: NavItem[];
}

export const navData: NavItem[] = [
  {
    name: 'Laptop',
    path: '/laptop',
    subItems: [
      { name: 'All Laptop', path: '/laptop/all', subItems: [
        { name: 'Asus', path: '/laptop/all/asus' },
        { name: 'Lenovo', path: '/laptop/all/lenovo' },
        { name: 'Dell', path: '/laptop/all/dell' },
        { name: 'Acer', path: '/laptop/all/acer' },
        { name: 'HP', path: '/laptop/all/hp' },
        { name: 'Apple', path: '/laptop/all/apple' },
      ]},
      { name: 'Budget Laptop', path: '/laptop/budget' },
      { name: 'Gaming Laptop', path: '/laptop/gaming' },
      { name: 'Premium Laptop', path: '/laptop/premium' },
      { name: 'Business Laptop', path: '/laptop/business' },
      { name: 'External Graphics Docks', path: '/laptop/external-graphics-docks' },
      { name: 'Laptop Accessories', path: '/laptop/accessories' },
    ],
  },
  {
    name: 'Desktop',
    path: '/desktop',
    subItems: [
      { name: 'All Desktop', path: '/desktop/all' },
      { name: 'Budget PC', path: '/desktop/budget-pc' },
      { name: 'Gaming PC', path: '/desktop/gaming-pc' },
      { name: 'NZXT PC', path: '/desktop/nzxt-pc' },
      { name: 'ASUS NUC', path: '/desktop/asus-nuc' },
      { name: 'All-in-One PC', path: '/desktop/all-in-one-pc' },
      { name: 'Brand PC', path: '/desktop/brand-pc' },
      { name: 'Asus Mini PC', path: '/desktop/asus-mini-pc' },
    ],
  },
  {
    name: 'Monitor',
    path: '/monitor',
    subItems: [
        { name: 'All Monitor', path: '/monitor/all' },
        { name: 'Gaming Monitor', path: '/monitor/gaming' },
        { name: '4K Monitor', path: '/monitor/4k' },
        { name: 'Curved Monitor', path: '/monitor/curved' },
        { name: 'Professional Monitor', path: '/monitor/professional' },
        { name: 'Business Monitor', path: '/monitor/business' },
        { name: 'Budget Monitor', path: '/monitor/budget' },
        { name: 'Portable Monitor', path: '/monitor/portable' },
        { name: 'Smart Monitor', path: '/monitor/smart' },
    ],
  },
  {
    name: 'Component',
    path: '/component',
    subItems: [
        { name: 'Motherboard', path: '/component/motherboard' },
        { name: 'Graphics Card', path: '/component/graphics-card' },
        { name: 'Processor', path: '/component/processor' },
        { name: 'CPU Cooler', path: '/component/cpu-cooler' },
        { name: 'Casing', path: '/component/casing' },
        { name: 'RAM', path: '/component/ram' },
        { name: 'SSD', path: '/component/ssd' },
        { name: 'Portable SSD', path: '/component/portable-ssd' },
        { name: 'HDD', path: '/component/hdd' },
        { name: 'Portable HDD', path: '/component/portable-hdd' },
        { name: 'Power Supply', path: '/component/power-supply' },
        { name: 'Power Station', path: '/component/power-station' },
        { name: 'UPS', path: '/component/ups' },
        { name: 'UPS Battery', path: '/component/ups-battery' },
        { name: 'Mini DC UPS', path: '/component/mini-dc-ups' },
        { name: 'DVD ROM', path: '/component/dvd-rom' },
        { name: 'Sound Card', path: '/component/sound-card' },
    ],
  },
  {
    name: 'Accessories',
    path: '/accessories',
    subItems: [
        { name: 'Keyboard & Mouse Combos', path: '/accessories/keyboard-mouse-combos' },
        { name: 'Keyboard', path: '/accessories/keyboard' },
        { name: 'Mouse', path: '/accessories/mouse' },
        { name: 'Mouse Pad', path: '/accessories/mouse-pad' },
        { name: 'Headphone', path: '/accessories/headphone' },
        { name: 'Earbuds', path: '/accessories/earbuds' },
        { name: 'Earphone', path: '/accessories/earphone' },
        { name: 'Speaker & Home Theater', path: '/accessories/speaker-home-theater' },
        { name: 'Bluetooth Speaker', path: '/accessories/bluetooth-speaker' },
        { name: 'Pendrive', path: '/accessories/pendrive' },
        { name: 'Memory Card', path: '/accessories/memory-card' },
        { name: 'Microphone', path: '/accessories/microphone' },
        { name: 'Power Bank', path: '/accessories/power-bank' },
        { name: 'Webcam', path: '/accessories/webcam' },
        { name: 'Mobile Accessories', path: '/accessories/mobile-accessories' },
        { name: 'Converter & Cable', path: '/accessories/converter-cable' },
        { name: 'Card Reader', path: '/accessories/card-reader' },
        { name: 'Bluetooth Receiver', path: '/accessories/bluetooth-receiver' },
        { name: 'HDD & SSD Enclosure', path: '/accessories/hdd-ssd-enclosure' },
        { name: 'Battery', path: '/accessories/battery' },
        { name: 'Car Accessories', path: '/accessories/car-accessories' },
        { name: 'Multi Plug', path: '/accessories/multi-plug' },
    ],
  },
  {
    name: 'Gadget',
    path: '/gadget',
    subItems: [
        { name: 'Gimbal', path: '/gadget/gimbal' },
        { name: 'Smartwatch', path: '/gadget/smartwatch' },
        { name: 'Action Camera', path: '/gadget/action-camera' },
    ],
  },
  {
    name: 'Office Equipment',
    path: '/office-equipment',
    subItems: [
        { name: 'Interactive Flat Panel', path: '/office-equipment/interactive-flat-panel' },
        { name: 'Professional Display Solution', path: '/office-equipment/professional-display-solution' },
        { name: 'Photocopier', path: '/office-equipment/photocopier' },
        { name: 'Projectors', path: '/office-equipment/projectors' },
        { name: 'Scanners', path: '/office-equipment/scanners' },
        { name: 'Fax', path: '/office-equipment/fax' },
        { name: 'CCTV Camera', path: '/office-equipment/cctv-camera' },
        { name: 'DVR/NVR/XVR', path: '/office-equipment/dvr-nvr-xvr' },
        { name: 'Access Control', path: '/office-equipment/access-control' },
        { name: 'Presenter', path: '/office-equipment/presenter' },
        { name: 'Conference Systems', path: '/office-equipment/conference-systems' },
        { name: 'Office Supplies', path: '/office-equipment/office-supplies' },
        { name: 'Software', path: '/office-equipment/software' },
    ],
  },
  {
    name: 'Gaming',
    path: '/gaming',
    subItems: [
        { name: 'Gamepad', path: '/gaming/gamepad' },
        { name: 'Gaming Console', path: '/gaming/console' },
        { name: 'Gaming Keyboard & Mouse Combo', path: '/gaming/keyboard-mouse-combo' },
        { name: 'Gaming Keyboard', path: '/gaming/keyboard' },
        { name: 'Gaming Mouse', path: '/gaming/mouse' },
        { name: 'Gaming Mouse Pad', path: '/gaming/mouse-pad' },
        { name: 'Gaming Headphone', path: '/gaming/headphone' },
        { name: 'Gaming Chair', path: '/gaming/chair' },
        { name: 'Gaming Desk', path: '/gaming/desk' },
        { name: 'Gaming Casing', path: '/gaming/casing' },
        { name: 'Gaming CPU Cooler', path: '/gaming/cpu-cooler' },
        { name: 'Gaming Motherboard', path: '/gaming/motherboard' },
        { name: 'Gaming Graphics Card', path: '/gaming/graphics-card' },
    ],
  },
  {
    name: 'Printer',
    path: '/printer',
    subItems: [
        { name: 'All Printer', path: '/printer/all' },
        { name: 'ID Card Printers', path: '/printer/id-card' },
        { name: 'Ink Tank Printers', path: '/printer/ink-tank' },
        { name: 'InkJet Printers', path: '/printer/inkjet' },
        { name: 'Label Printers', path: '/printer/label' },
        { name: 'Large Format Printers', path: '/printer/large-format' },
        { name: 'Laser Printers', path: '/printer/laser' },
        { name: 'POS Printer', path: '/printer/pos' },
        { name: 'Dot Matrix Printer', path: '/printer/dot-matrix' },
        { name: 'Toner/Drum/Cartridge', path: '/printer/toner-drum-cartridge' },
        { name: 'Printer Accessories', path: '/printer/accessories' },
    ],
  },
  {
    name: 'Networking',
    path: '/networking',
    subItems: [
        { name: 'Starlink', path: '/networking/starlink' },
        { name: 'Router', path: '/networking/router' },
        { name: 'Access Point & Extender', path: '/networking/access-point-extender' },
        { name: 'LAN Card & WiFi Adapter', path: '/networking/lan-card-wifi-adapter' },
        { name: 'Switch', path: '/networking/switch' },
        { name: 'Firewall', path: '/networking/firewall' },
        { name: 'Gateway Router', path: '/networking/gateway-router' },
        { name: 'Network Rack', path: '/networking/network-rack' },
        { name: 'Network Rack Accessories', path: '/networking/network-rack-accessories' },
        { name: 'Network Cables', path: '/networking/network-cables' },
        { name: 'Network Cables Accessories', path: '/networking/network-cables-accessories' },
        { name: 'ONU', path: '/networking/onu' },
        { name: 'OLT', path: '/networking/olt' },
        { name: 'Network Tools', path: '/networking/network-tools' },
    ],
  },
  {
    name: 'SME Networking',
    path: '/sme-networking',
    subItems: [
        { name: 'Ruijie', path: '/sme-networking/ruijie' },
        { name: 'Huawei Toolkit', path: '/sme-networking/huawei-toolkit' },
    ],
  },
  {
    name: 'Server & Storage',
    path: '/server-storage',
    subItems: [
        { name: 'Server', path: '/server-storage/server' },
        { name: 'Storage', path: '/server-storage/storage' },
        { name: 'Server Rack', path: '/server-storage/server-rack' },
        { name: 'Workstation', path: '/server-storage/workstation' },
        { name: 'Enterprise HDD', path: '/server-storage/enterprise-hdd' },
    ],
  },
];
